version: '3.8'

services:
  landing:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development  # Changed to development for hot reload
    volumes:
      - ./landing-page:/app  # Mounts local landing-page to /app in container
      - /app/node_modules  # Excludes node_modules to avoid conflicts
    networks:
      - arktechnologies
    restart: unless-stopped

  demo:
    build:
      context: ./flyleaf-demo
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - arktechnologies
    restart: unless-stopped

volumes:
  redis_data:
  n8n_data:
  ollama_data:
  grafana_data:
  prometheus_data:

networks:
  arktechnologies:
    driver: bridge