version: '3.8'

services:
  landing:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - arktechnologies
    restart: unless-stopped

  demo:
    build:
      context: ./flyleaf-demo
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - arktechnologies
    restart: unless-stopped

volumes:
  redis_data:
  n8n_data:
  ollama_data:
  grafana_data:
  prometheus_data:

networks:
  arktechnologies:
    driver: bridge
