version: '3.8'

services:
  landing:
    build:
      context: ./landing-page
      dockerfile: Dockerfile
    container_name: arktechnologies-landing
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./landing-page:/app
      - /app/node_modules
      - /app/.next  # Exclude .next directory to avoid conflicts
    networks:
      - arktechnologies
    restart: unless-stopped

  demo:
    build:
      context: ./flyleaf-demo1  # Updated to match your folder name
      dockerfile: Dockerfile
    container_name: arktechnologies-demo
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - arktechnologies
    restart: unless-stopped

volumes:
  redis_data:
  n8n_data:
  ollama_data:
  grafana_data:
  prometheus_data:

networks:
  arktechnologies:
    driver: bridge
